# Generated by Django 3.2.15 on 2022-08-27 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='vote_count',
        ),
    ]
