# Generated by Django 3.2.15 on 2022-08-11 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20220811_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='vote_count',
        ),
    ]
